-- Friend requests -------------------------------------------------------------------------------
--
-- "Add Friend" used to be a one-sided bookmark: it inserted straight into `friends` with no
-- involvement from the other person at all, so anyone could silently add anyone. This table makes
-- it a real request the other person has to accept, the way the client's inbox dropdown expects:
--
--   1. Sender picks "Add Friend" -> app inserts one row here (sender_id = them, recipient_id =
--      the target, status = 'pending').
--   2. Recipient's client is subscribed to rows naming them as recipient_id, so the pending
--      request shows up live in their request inbox with no reload needed.
--   3. Accept: recipient inserts their own `friends` row (owner_id = them, friend_id = sender),
--      then flips this row's status to 'accepted'. The sender's client is watching this same row
--      (it's also visible to them, since select covers both sides) and reacts to the status flip
--      by inserting ITS OWN `friends` row (owner_id = sender, friend_id = recipient) -- that
--      mirror-insert-on-both-sides dance is what turns a one-way request into a mutual friendship,
--      without needing a privileged server-side function: each side only ever inserts a `friends`
--      row naming themselves as owner_id, which the existing `friends` RLS already allows.
--   4. Decline: recipient flips status to 'declined'. Sender's client quietly drops it from their
--      pending state -- no row ever gets added to `friends`, and (by convention, not enforced
--      here) the UI does not tell the sender they were declined.
--   5. Cancel: sender can flip their own still-pending row to 'cancelled' if they change their
--      mind before the other person responds.
--
-- Run this once in the Supabase SQL Editor.

create table if not exists public.friend_requests (
  id             bigint generated by default as identity primary key,
  sender_id      uuid        not null references auth.users(id) on delete cascade,
  sender_name    text,
  recipient_id   uuid        not null references auth.users(id) on delete cascade,
  recipient_name text,
  status         text        not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at     timestamptz not null default now(),
  responded_at   timestamptz,
  check (sender_id <> recipient_id)
);

-- Only one pending request per direction at a time -- resending after a decline/cancel is fine
-- (that's a fresh row), it's a second SIMULTANEOUS pending one from the same sender that's blocked.
create unique index if not exists friend_requests_one_pending_per_direction
  on public.friend_requests (sender_id, recipient_id) where (status = 'pending');

create index if not exists friend_requests_recipient on public.friend_requests (recipient_id, status);
create index if not exists friend_requests_sender on public.friend_requests (sender_id, status);

alter table public.friend_requests enable row level security;

-- Both sides of a request can see it: the recipient needs it for their inbox, the sender needs it
-- to notice a decline/cancel/accept happen so their client can react (see step 3 above).
create policy "see own friend requests" on public.friend_requests for select to authenticated
  using (sender_id = auth.uid() or recipient_id = auth.uid());

-- You can only ever send a request as yourself, to someone else, and it always starts pending --
-- the client doesn't get to insert a pre-accepted row.
create policy "send friend request" on public.friend_requests for insert to authenticated
  with check (sender_id = auth.uid() and recipient_id <> auth.uid() and status = 'pending');

-- Either side can update a request that names them: the recipient accepts/declines, the sender
-- cancels. Not carving this up further per-column/per-transition here -- same trust level as the
-- rest of this app's RLS (e.g. friends' own update policy, moveFriendGroup).
create policy "respond to own friend requests" on public.friend_requests for update to authenticated
  using (sender_id = auth.uid() or recipient_id = auth.uid())
  with check (sender_id = auth.uid() or recipient_id = auth.uid());

-- Live inbox: a pending request appearing, and a status flip (accepted/declined/cancelled), both
-- need to reach the other party's open tab without a reload.
alter publication supabase_realtime add table public.friend_requests;
